### ISSUE TITLE
Large amount of selectable columns

### ISSUE THREAD

**Issue by silveltman** [DennisSnijder/payload-workflow#3]
When going to the columns tab and selecting one, a duplicate is created each time. This leads to something like the following:

![Screenshot 2023-10-12 at 13 45 52](https://github.com/DennisSnijder/payload-workflow/assets/52583398/6ec4997b-74e7-4fbe-bd42-18e2b316dd6b)

**Comment by DennisSnijder** [comment]
Thanks for the report! I will be looking into it 😄

**Comment by DennisSnijder** [comment]
Hi @silveltman 

I can't seem to reproduce the bug on my end... 

https://github.com/DennisSnijder/payload-workflow/assets/6953846/e51e8de9-19a8-4d88-b582-0a7c32d448d6

**Comment by zakinadhif** [comment]
Make sure you don't have multiple field with the same name!

**Comment by silveltman** [comment]
I might have had multiple fields with the same name for testing something else. Anyway, don't have the issue anymore so i'm closing this issue for now.

Thanks for thinking along!
