### ISSUE TITLE
Admin components are being overridden by the plugin's config

### ISSUE THREAD

**Issue by jacobsfletch** [DennisSnijder/payload-workflow#6]
This line adds a custom List view to the collection, but does not spread the user's `admin.components` config back in: https://github.com/DennisSnijder/payload-workflow/blob/main/src/index.ts#L57. This means that when using this plugin, you cannot bring your own custom components with it. It's a simple fix:

```ts
// Collection.ts
{
  // ...
  admin: {
    // ...
    components: {
      ...collection?.admin?.components || {}, // THIS LINE FIXES IT
      views: {
        ...collection?.admin?.components?.views || {},
        List: WorkflowView(collectionPluginConfig)
      }
    }
  }
}
```

**Comment by DennisSnijder** [comment]
Hi @jacobsfletch ! 

Thanks for reporting this! good catch! I'll patch this ASAP!
